const SagaActions = {
	GEG_ALL_TAGS: 'GEG_ALL_TAGS',
	CREATE_TAG: 'CREATE_TAG',

	GET_ALL_QUESTIONS: 'GET_ALL_QUESTIONS',
	CREATE_QUESTION: 'CREATE_QUESTION',

	GET_MY_PROFILE: 'GET_MY_PROFILE',
	GET_USER_PROFILE: 'GET_USER_PROFILE',

	DEFINE_AUTH: 'DEFINE_AUTH',
	LOG_OUT: 'LOG_OUT',
};

export default SagaActions;
